export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const ITEMS_LOADING= 'ITEMS_LOADING'